# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'CSE535_Project' do

pod 'Firebase', '>= 1.2.3'
pod 'Facebook-iOS-SDK', '>=3.21.1'

end

target 'CSE535_ProjectTests' do

end

